export const timePickerTokens = {
    inputBg: 'var(--surface-base)',
    inputBorderColor: 'var(--border-primary)',
    inputFocusBorderColor: 'var(--intent-primary)',
    inputTextColor: 'var(--text-primary)',
    inputPlaceholderColor: 'var(--text-muted)',
    labelColor: 'var(--text-secondary)',
    errorColor: 'var(--intent-danger)',
    helperColor: 'var(--text-muted)',
    popupBg: 'var(--surface-raised)',
    popupBorderColor: 'var(--border-primary)',
    columnHeaderColor: 'var(--text-muted)',
    itemTextColor: 'var(--text-primary)',
    itemHoverBg: 'var(--surface-sunken)',
    itemSelectedBg: 'var(--intent-primary)',
    itemSelectedColor: '#ffffff',
    separatorColor: 'var(--text-muted)',
    borderRadius: 'var(--radius-md)',
    popupRadius: 'var(--radius-lg)',
} as const;
