export const datePickerTokens = {
    inputBg: 'var(--surface-base)',
    inputBorderColor: 'var(--border-primary)',
    inputFocusBorderColor: 'var(--intent-primary)',
    inputTextColor: 'var(--text-primary)',
    inputPlaceholderColor: 'var(--text-muted)',
    labelColor: 'var(--text-secondary)',
    errorColor: 'var(--intent-danger)',
    helperColor: 'var(--text-muted)',
    calendarBg: 'var(--surface-raised)',
    calendarBorderColor: 'var(--border-primary)',
    calendarHeaderColor: 'var(--text-primary)',
    dayTextColor: 'var(--text-primary)',
    dayMutedColor: 'var(--text-muted)',
    dayHoverBg: 'var(--surface-sunken)',
    daySelectedBg: 'var(--intent-primary)',
    daySelectedColor: '#ffffff',
    dayTodayBorderColor: 'var(--intent-primary)',
    borderRadius: 'var(--radius-md)',
    calendarRadius: 'var(--radius-lg)',
} as const;
